# Generated by Django 6.0.4 on 2026-04-24 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('perfil', models.CharField(choices=[('Administrador', 'Administrador'), ('Funcionário', 'Funcionário'), ('Aluno', 'Aluno')], max_length=20)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('id_funcionario', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade_nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('horario', models.CharField(help_text='Formato HH:MM', max_length=10)),
                ('dias_semana', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Modalidade',
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plano', models.CharField(max_length=100, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('modalidades_inclusas', models.PositiveIntegerField(help_text='Quantidade de modalidades permitidas')),
                ('duracao_meses', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=15)),
                ('aluno', models.ForeignKey(limit_choices_to={'perfil': 'Aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to=settings.AUTH_USER_MODEL)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.modalidade')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'perfil': 'Aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='historico', to=settings.AUTH_USER_MODEL)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.modalidade')),
            ],
            options={
                'verbose_name': 'Frequência',
                'verbose_name_plural': 'Frequências',
                'ordering': ['-data', '-hora'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='modalidades_inscritas',
            field=models.ManyToManyField(blank=True, related_name='alunos_inscritos', to='academia.modalidade'),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mes_ano', models.CharField(help_text='Formato MM/AAAA', max_length=7)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado')], default='pendente', max_length=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'perfil': 'Aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-mes_ano'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='academia.plano'),
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_muscular', models.CharField(max_length=100)),
                ('exercicios', models.JSONField(default=list, help_text='Lista de exercícios')),
                ('series', models.PositiveIntegerField()),
                ('repeticoes', models.PositiveIntegerField()),
                ('data', models.DateField()),
                ('aluno', models.ForeignKey(limit_choices_to={'perfil': 'Aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='historico_treinos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Treino',
                'verbose_name_plural': 'Treinos',
                'ordering': ['-data'],
            },
        ),
    ]
