# Generated by Django 6.0.4 on 2026-05-24 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0001_initial'),
        ('modalidades', '0001_initial'),
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='modalidades_inscritas',
            field=models.ManyToManyField(blank=True, related_name='alunos_inscritos', to='modalidades.modalidade'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='planos.plano'),
        ),
    ]
