# Generated by Django 6.0.4 on 2026-05-13 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_usuario_is_active'),
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='modalidade',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='modalidade',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='aluno',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='planos.plano'),
        ),
        migrations.RemoveField(
            model_name='treino',
            name='aluno',
        ),
    ]
