# Generated by Django 6.0.4 on 2026-05-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_remove_frequencia_aluno_remove_frequencia_modalidade_and_more'),
        ('modalidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='modalidades_inscritas',
            field=models.ManyToManyField(blank=True, related_name='alunos_inscritos', to='modalidades.modalidade'),
        ),
        migrations.DeleteModel(
            name='Frequencia',
        ),
        migrations.DeleteModel(
            name='Inscricao',
        ),
        migrations.DeleteModel(
            name='Modalidade',
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
        migrations.DeleteModel(
            name='Plano',
        ),
        migrations.DeleteModel(
            name='Treino',
        ),
    ]
