# Generated by Django 6.0.4 on 2026-05-24 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id_treino', models.AutoField(primary_key=True, serialize=False)),
                ('nome_treino', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('grupo_muscular', models.CharField(max_length=100)),
                ('exercicios', models.JSONField(default=list, help_text='Lista de exercícios')),
                ('series', models.PositiveIntegerField()),
                ('repeticoes', models.PositiveIntegerField()),
                ('data', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_treinos', to='academia.aluno')),
            ],
            options={
                'verbose_name': 'Treino',
                'verbose_name_plural': 'Treinos',
                'ordering': ['-data'],
            },
        ),
    ]
