# Generated by Django 6.0.4 on 2026-05-24 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade_nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('horario', models.CharField(help_text='Formato HH:MM', max_length=10)),
                ('dias_semana', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Modalidade',
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=15)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='academia.aluno')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modalidades.modalidade')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='academia.aluno')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modalidades.modalidade')),
            ],
            options={
                'verbose_name': 'Frequência',
                'verbose_name_plural': 'Frequências',
                'ordering': ['-data', '-hora'],
            },
        ),
    ]
